version: "3"

services:
  redis-stack:
    image: docker.io/redis/redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - "redis-data:/data"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

  minio:
    image: docker.io/minio/minio
    ports:
      - "9000:9000"
      - "8900:8900"
    volumes:
      - "minio-data:/data/minio"
    environment:
      MINIO_ROOT_USER: miniosudo
      MINIO_ROOT_PASSWORD: miniosudo
    command: minio server /data/minio --console-address ":8900"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
      retries: 3
      timeout: 5s

  minio-client:
    image: docker.io/minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 miniosudo miniosudo;
      /usr/bin/mc rm -r --force myminio/local;
      /usr/bin/mc mb myminio/local;
      /usr/bin/mc policy set download myminio/local;
      exit 0;
      "
