version: '3'

services:
  redis-stack:
    image: docker.io/redis/redis-stack
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - 'redis-data:/data'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      retries: 3
      timeout: 5s
